version: "3"
services:
  mysqldb:
    container_name: mysql-container
    image: mysql
    restart: always
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "devops"
      MYSQL_ROOT_PASSWORD: "root"
    networks:
      - mynetwork
  app:
    depends_on:
      - mysqldb
    image: amanihadda/springproject:tag123
    restart: always
    ports:
      - "8082:8082"
    environment:
      spring.datasource.url: "jdbc:mysql://mysql-container:3306/devops?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
      MYSQL_HOST: "mysql-container"
      MYSQL_USER: "root"
      MYSQL_PASSWORD:
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db:
